#!/usr/bin/env bash
set -euo pipefail

ROOT="${1:-$PWD}"

python3 - "$ROOT" <<'PY'
import datetime
import re
import sys
from pathlib import Path

root = Path(sys.argv[1]).resolve()
refs = root / "references"
wiki = refs / "wiki"
raw = refs / "raw"
index = refs / "_index.md"
required = {"title", "context", "category", "concept", "description", "tags", "sources", "last_ingested"}
scalar = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*):\s*(.*)$")
hard = 0
soft = 0


def parse_frontmatter(path):
    fields = {}
    sources = []
    in_sources = False
    lines = path.read_text().splitlines()
    if not lines or lines[0] != "---":
        return fields, sources
    for line in lines[1:]:
        if line == "---":
            break
        if in_sources:
            stripped = line.strip()
            if stripped.startswith("- "):
                sources.append(stripped[2:].strip().strip("\"'"))
                continue
            if stripped == "":
                continue
            in_sources = False
        if line.startswith("sources:"):
            fields["sources"] = True
            in_sources = line.strip() == "sources:"
            continue
        match = scalar.match(line)
        if match and match.group(2).strip():
            fields[match.group(1)] = match.group(2).strip().strip("\"'")
    return fields, sources


wiki_files = sorted(wiki.rglob("*.md")) if wiki.exists() else []
raw_files = sorted(p for p in raw.rglob("*") if p.is_file() and p.name != ".gitkeep") if raw.exists() else []
meta = {}
contexts = {}
citations = set()

for path in wiki_files:
    rel = path.relative_to(root).as_posix()
    parts = path.relative_to(wiki).parts
    fields, sources = parse_frontmatter(path)
    meta[path] = (fields, sources)
    missing = sorted(required - set(fields))
    if len(parts) != 3:
        print(f"FAIL {rel}: expected references/wiki/<context>/<category>/<concept>.md")
        hard += 1
        continue
    ctx, category, filename = parts
    concept = filename.removesuffix(".md")
    contexts.setdefault(ctx, set()).add(category)
    if missing:
        print(f"FAIL {rel}: missing {', '.join(missing)}")
        hard += 1
    if (fields.get("context"), fields.get("category"), fields.get("concept")) != (ctx, category, concept):
        print(f"FAIL {rel}: path/frontmatter mismatch")
        hard += 1
    for source in sources:
        citations.add(source)
        if not source.startswith("references/raw/") or not (root / source).exists():
            print(f"FAIL {rel}: broken source {source}")
            hard += 1
    if not sources:
        print(f"WARN {rel}: empty sources")
        soft += 1

for path in raw_files:
    rel = path.relative_to(root).as_posix()
    if rel not in citations:
        print(f"WARN {rel}: orphan raw")
        soft += 1

body = [
    "# Index\n\n",
    "Auto-generated by `scripts/lint.sh` from the filesystem walk of\n",
    "`references/wiki/`, `references/raw/`, and `scripts/`. Do not hand-edit\n",
    "below the generated markers. To change the taxonomy, add or remove wiki\n",
    "files and re-run lint.\n\n",
    "<!-- GENERATED:START -->\n\n",
    "## Summary\n\n",
    "Context -> categories. See `## Wiki` below for the concept enumeration.\n\n",
]
for ctx in sorted(contexts):
    cats = ", ".join(f"`{cat}`" for cat in sorted(contexts[ctx]))
    body.append(f"- **{ctx}** -> {cats}\n")
body.append("\n## Wiki\n\n")
for ctx in sorted(contexts):
    body.append(f"### {ctx}\n\n")
    for category in sorted(contexts[ctx]):
        body.append(f"#### {category}\n\n")
        for path in wiki_files:
            fields, _ = meta[path]
            if fields.get("context") == ctx and fields.get("category") == category:
                link = path.relative_to(refs).as_posix()
                body.append(f"- [{fields.get('concept', path.stem)}.md]({link}) - {fields.get('title', path.stem)}\n")
        body.append("\n")
body.append("---\n\n## Raw Sources\n\n")
for path in raw_files:
    rel = path.relative_to(root).as_posix()
    citers = [p.relative_to(root).as_posix() for p, (_, srcs) in meta.items() if rel in srcs]
    suffix = f"cited by: {', '.join(sorted(citers))}" if citers else "(not cited; orphan)"
    body.append(f"- [{path.name}]({path.relative_to(refs).as_posix()}) - {suffix}\n")
body.append("\n---\n\n## Scripts\n\n")
for path in sorted((root / "scripts").glob("*")) if (root / "scripts").exists() else []:
    if path.is_file() and path.suffix in {".sh", ".py"}:
        body.append(f"- [scripts/{path.name}](../scripts/{path.name})\n")
body.append("\n<!-- GENERATED:END -->\n")
index.write_text("".join(body))

log = refs / "log.md"
with log.open("a") as handle:
    today = datetime.date.today().isoformat()
    handle.write(f"\n[LINT {today}] {len(wiki_files)} wiki, {len(raw_files)} raw. Hard: {hard}, Soft: {soft}. Regenerated _index.md.\n")

print(f"wiki={len(wiki_files)} raw={len(raw_files)} hard={hard} soft={soft}")
sys.exit(1 if hard else 0)
PY
